name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch:

jobs:
  test:
    # if: |
    #   github.repository == 'NCAR/geocat-comp'
    name: Python (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: conda_setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: geocat_comp_build
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          environment-file: build_envs/environment.yml

      - name: Install geocat-comp
        run: |
          python -m pip install . --no-deps

      - name: conda list
        run: |
          conda list

      - name: Run Namespace Tests
        run: |
          python -m pytest test

      - name: Run Coverage Tests
        run: |
          python -m pytest test -v --cov=./src/geocat/comp --cov-report=xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
      - name: Open Issue on Failure
        if: github.ref_name = 'main' && github.event.state == 'error' || github.event.state == 'failure'
        env:
          DESCRIPTION: ${{ github.event.description }}
          COMMIT: ${{ github.sha }}
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "geocat"
          labels: "high priority, bug"
          title: "Main Branch Failed A Check"
          body: |
            The `main` branch failed after $COMMIT was merged into it.
            
            $DESCRIPTION
            
          pinned: true

  link-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: conda_setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gc-docs
          channel-priority: strict
          python-version: 3.9
          channels: conda-forge
          environment-file: build_envs/docs.yml
      - name: Make docs with linkcheck
        run: |
          cd docs
          make linkcheck
          
