on:
  status
jobs:
  if_error_or_failure:
    name: Main failure
    runs-on: ubuntu-latest
    if: github.ref_name = 'main' && github.event.state == 'error' || github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
